name: Flutter CI

on:
  push:
    paths:
      - "app/**"
      - ".github/workflows/flutter-ci.yml"

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter and Dependencies
        uses: ./.github/workflows/common/flutter-setup

      - name: Run Flutter Analyze
        working-directory: app
        run: flutter analyze

      - name: Run Custom Lint
        working-directory: app
        run: dart run custom_lint

      - name: Run Tests
        working-directory: app
        run: flutter test
